//! Observation rules: which applications and URL domains the recorder may
//! observe. The model follows the Codex "Computer History" observation
//! settings (`ComputerUseIPCSkysightObservationSettings`) — two independent
//! rule lists (allowlist / blocklist) over two scopes (`application` / `url`),
//! a default behavior per scope, and a small set of hardcoded safety
//! exclusions that no rule can override.

use serde::{Deserialize, Serialize};

use nomifun_common::AppError;

/// Scope of an observation rule. Wire values are the snake_case strings the
/// Codex IPC surface uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleScope {
    Application,
    Url,
}

/// What a matched rule (or a default behavior) instructs the recorder to do.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DefaultBehavior {
    Observe,
    DoNotObserve,
}

/// Per-rule action kept for nomifun-style rule storage (capture vs ignore).
/// `Redact` keeps the event but scrubs captured text before persistence.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleAction {
    #[default]
    Capture,
    Ignore,
    Redact,
}

/// One observation rule. An application rule needs a non-empty `bundle_id`;
/// a URL rule needs a valid `url_domain` (no scheme, no path). Validation
/// messages are adapted verbatim from the Codex string table.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActivityRule {
    /// Bare UUIDv7 rule id (generated by the store when absent).
    #[serde(default)]
    pub id: String,
    pub scope: RuleScope,
    /// Required only for app rules.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bundle_id: Option<String>,
    /// Required only for URL rules. Use a domain without a scheme or path.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url_domain: Option<String>,
    #[serde(default)]
    pub action: RuleAction,
}

/// Hardcoded app exclusions from the Codex string table — Window Manager,
/// Control Center, Notification Center and the local-authentication UI agent
/// are never observed regardless of rules or defaults.
pub const HARDCODED_EXCLUDED_BUNDLE_IDS: &[&str] = &[
    "com.apple.WindowManager",
    "com.apple.controlcenter",
    "com.apple.notificationcenterui",
    "com.apple.LocalAuthentication.UIAgent",
];

/// The full observation settings object. `computer_history_get_settings`
/// returns this whole object and `computer_history_update_settings` replaces
/// it, so callers must fetch first and re-send unchanged fields.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ObservationSettings {
    #[serde(rename = "defaultApplicationBehavior")]
    pub default_application_behavior: DefaultBehavior,
    #[serde(rename = "defaultURLBehavior")]
    pub default_url_behavior: DefaultBehavior,
    #[serde(rename = "observePrivateBrowsing", default)]
    pub observe_private_browsing: bool,
    #[serde(default)]
    pub allowlist: Vec<ActivityRule>,
    #[serde(default)]
    pub blocklist: Vec<ActivityRule>,
}

impl Default for ObservationSettings {
    fn default() -> Self {
        // Fresh-install defaults are not recoverable from the Codex binary
        // (spec §9.4); observe-by-default with private browsing excluded is
        // the conservative reading of the observed field set.
        Self {
            default_application_behavior: DefaultBehavior::Observe,
            default_url_behavior: DefaultBehavior::Observe,
            observe_private_browsing: false,
            allowlist: Vec::new(),
            blocklist: Vec::new(),
        }
    }
}

/// Is a bundle id allowed by the rule lists + defaults? Hardcoded exclusions
/// win first. `is_private_browsing` windows are suppressed unless
/// `observe_private_browsing` is set (suppression reason:
/// `privateBrowsingExcluded`).
pub fn observe_application(settings: &ObservationSettings, bundle_id: &str) -> bool {
    if HARDCODED_EXCLUDED_BUNDLE_IDS.contains(&bundle_id) {
        return false; // reason: applicationExcluded
    }
    match find_rule(settings, RuleScope::Application, bundle_id) {
        Some(rule) => rule.action != RuleAction::Ignore,
        None => settings.default_application_behavior == DefaultBehavior::Observe,
    }
}

/// Is a URL domain observable? Rules are matched case-insensitively against
/// the registrable domain (subdomain semantics are unspecified in Codex —
/// spec §9.5 — so we match the exact domain or a subdomain of it).
pub fn observe_url_domain(settings: &ObservationSettings, url_domain: &str) -> bool {
    let domain = url_domain.trim().to_ascii_lowercase();
    if domain.is_empty() {
        return false;
    }
    match find_rule(settings, RuleScope::Url, &domain) {
        Some(rule) => rule.action != RuleAction::Ignore,
        None => settings.default_url_behavior == DefaultBehavior::Observe,
    }
}

/// Redaction discipline for captured text: nomi-redact first (best-effort
/// secret scrubbing), then the Codex-style token-table hint is already covered
/// by the secret-assignment regex. Text captured while macOS Secure Input is
/// active never reaches this function — the observer withholds it entirely.
pub fn redact_captured_text(input: &str) -> String {
    nomi_redact::redact_secrets(input).into_owned()
}

fn find_rule<'a>(
    settings: &'a ObservationSettings,
    scope: RuleScope,
    key: &str,
) -> Option<&'a ActivityRule> {
    let key = key.to_ascii_lowercase();
    fn matches<'a>(
        rules: &'a [ActivityRule],
        scope: RuleScope,
        key: &str,
    ) -> Option<&'a ActivityRule> {
        rules.iter().find(|rule| {
            if rule.scope != scope {
                return false;
            }
            let pattern = match scope {
                RuleScope::Application => rule.bundle_id.as_deref().unwrap_or(""),
                RuleScope::Url => rule.url_domain.as_deref().unwrap_or(""),
            };
            let pattern = pattern.trim().to_ascii_lowercase();
            if pattern.is_empty() {
                return false;
            }
            // Exact match, or the key is a subdomain of the rule domain.
            key == pattern || (scope == RuleScope::Url && key.ends_with(&format!(".{pattern}")))
        })
    }
    // Blocklist wins over allowlist, mirroring deny-overrides-allow policy.
    matches(&settings.blocklist, scope, &key).or_else(|| matches(&settings.allowlist, scope, &key))
}

/// Validate one rule, adapting the Codex validation strings.
fn validate_rule(rule: &ActivityRule) -> Result<(), AppError> {
    match rule.scope {
        RuleScope::Application => {
            let bundle = rule
                .bundle_id
                .as_deref()
                .map(str::trim)
                .unwrap_or_default();
            if bundle.is_empty() || rule.url_domain.as_deref().map_or(false, |d| !d.is_empty()) {
                return Err(AppError::BadRequest(
                    "Computer History app observation rules require only a non-empty bundleID."
                        .into(),
                ));
            }
        }
        RuleScope::Url => {
            let domain = rule.url_domain.as_deref().map(str::trim).unwrap_or_default();
            let valid = !domain.is_empty()
                && !domain.contains("://")
                && !domain.contains('/')
                && !domain.contains(' ')
                && rule.bundle_id.as_deref().map_or(true, |b| b.is_empty());
            if !valid {
                return Err(AppError::BadRequest(
                    "Computer History URL observation rules require only a valid urlDomain."
                        .into(),
                ));
            }
        }
    }
    Ok(())
}

impl ActivityRule {
    /// Validate and normalize (trimmed identifiers).
    pub fn validated(mut self) -> Result<Self, AppError> {
        self.bundle_id = self.bundle_id.take().map(|b| b.trim().to_string());
        self.url_domain = self.url_domain.take().map(|d| d.trim().to_string());
        validate_rule(&self)?;
        Ok(self)
    }
}

impl ObservationSettings {
    /// Validate every stored rule.
    pub fn validated(mut self) -> Result<Self, AppError> {
        let mut allowlist = Vec::with_capacity(self.allowlist.len());
        for rule in self.allowlist.drain(..) {
            allowlist.push(rule.validated()?);
        }
        let mut blocklist = Vec::with_capacity(self.blocklist.len());
        for rule in self.blocklist.drain(..) {
            blocklist.push(rule.validated()?);
        }
        self.allowlist = allowlist;
        self.blocklist = blocklist;
        Ok(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn app_rule(bundle: &str) -> ActivityRule {
        ActivityRule {
            id: nomifun_common::generate_id(),
            scope: RuleScope::Application,
            bundle_id: Some(bundle.into()),
            url_domain: None,
            action: RuleAction::Ignore,
        }
        .validated()
        .unwrap()
    }

    fn url_rule(domain: &str) -> ActivityRule {
        ActivityRule {
            id: nomifun_common::generate_id(),
            scope: RuleScope::Url,
            bundle_id: None,
            url_domain: Some(domain.into()),
            action: RuleAction::Ignore,
        }
        .validated()
        .unwrap()
    }

    #[test]
    fn hardcoded_exclusions_win() {
        for bundle in HARDCODED_EXCLUDED_BUNDLE_IDS {
            assert!(!observe_application(&ObservationSettings::default(), bundle));
        }
    }

    #[test]
    fn blocklist_overrides_default() {
        let settings = ObservationSettings {
            blocklist: vec![app_rule("com.example.app")],
            ..ObservationSettings::default()
        };
        assert!(!observe_application(&settings, "com.example.app"));
        assert!(observe_application(&settings, "com.other.app"));
    }

    #[test]
    fn allowlist_gates_when_default_is_do_not_observe() {
        let settings = ObservationSettings {
            default_application_behavior: DefaultBehavior::DoNotObserve,
            allowlist: vec![ActivityRule {
                action: RuleAction::Capture,
                ..app_rule("com.allowed.app")
            }],
            ..ObservationSettings::default()
        };
        assert!(observe_application(&settings, "com.allowed.app"));
        assert!(!observe_application(&settings, "com.denied.app"));
    }

    #[test]
    fn url_rules_match_subdomains() {
        let settings = ObservationSettings {
            blocklist: vec![url_rule("example.com")],
            ..ObservationSettings::default()
        };
        assert!(!observe_url_domain(&settings, "example.com"));
        assert!(!observe_url_domain(&settings, "docs.example.com"));
        assert!(observe_url_domain(&settings, "notexample.com"));
        assert!(!observe_url_domain(&settings, ""));
    }

    #[test]
    fn private_browsing_is_suppressed_by_default() {
        let settings = ObservationSettings::default();
        assert!(!settings.observe_private_browsing);
    }

    #[test]
    fn app_rule_rejects_empty_bundle_and_stray_domain() {
        let empty = ActivityRule {
            id: nomifun_common::generate_id(),
            scope: RuleScope::Application,
            bundle_id: Some("  ".into()),
            url_domain: None,
            action: RuleAction::Capture,
        };
        assert_eq!(
            empty.validated().unwrap_err().to_string(),
            "Bad request: Computer History app observation rules require only a non-empty bundleID."
        );
        let mixed = ActivityRule {
            id: nomifun_common::generate_id(),
            scope: RuleScope::Application,
            bundle_id: Some("com.example.app".into()),
            url_domain: Some("example.com".into()),
            action: RuleAction::Capture,
        };
        assert_eq!(
            mixed.validated().unwrap_err().to_string(),
            "Bad request: Computer History app observation rules require only a non-empty bundleID."
        );
    }

    #[test]
    fn url_rule_rejects_scheme_path_and_stray_bundle() {
        for domain in ["https://example.com", "example.com/path", "", "   "] {
            let rule = ActivityRule {
                id: nomifun_common::generate_id(),
                scope: RuleScope::Url,
                bundle_id: None,
                url_domain: Some(domain.into()),
                action: RuleAction::Capture,
            };
            assert_eq!(
                rule.validated().unwrap_err().to_string(),
                "Bad request: Computer History URL observation rules require only a valid urlDomain."
            );
        }
        let mixed = ActivityRule {
            id: nomifun_common::generate_id(),
            scope: RuleScope::Url,
            bundle_id: Some("com.example.app".into()),
            url_domain: Some("example.com".into()),
            action: RuleAction::Capture,
        };
        assert_eq!(
            mixed.validated().unwrap_err().to_string(),
            "Bad request: Computer History URL observation rules require only a valid urlDomain."
        );
    }

    #[test]
    fn redact_captured_text_scrubs_secrets() {
        let out = redact_captured_text("token: supersecretvalue123");
        assert!(out.contains("[REDACTED_SECRET]"));
        assert!(!out.contains("supersecretvalue123"));
    }

    #[test]
    fn settings_roundtrip_uses_camel_case_wire_keys() {
        let settings = ObservationSettings::default();
        let json = serde_json::to_value(&settings).unwrap();
        assert!(json.get("defaultApplicationBehavior").is_some());
        assert!(json.get("defaultURLBehavior").is_some());
        assert!(json.get("observePrivateBrowsing").is_some());
        let parsed: ObservationSettings = serde_json::from_value(json).unwrap();
        assert_eq!(parsed, settings);
        assert!(serde_json::from_value::<ObservationSettings>(serde_json::json!({
            "defaultApplicationBehavior": "observe",
            "defaultURLBehavior": "observe",
            "observePrivateBrowsing": false,
            "unknown": 1
        }))
        .is_err());
    }
}
