//! Feature-local activity store, modeled on
//! `nomifun-companion/src/store.rs`: own SQLite file (WAL), its own schema
//! contract, writes serialized through a small pool. This is deliberately NOT
//! part of the nomifun-db migration lineage — computer history is high-write,
//! disposable data.
//!
//! Schema follows the repo v3 conventions: `id INTEGER PRIMARY KEY
//! AUTOINCREMENT`, bare UUIDv7 string identifiers, **no physical foreign
//! keys** — logical references are maintained by the writer with indexes.

use std::path::Path;

use nomifun_common::{AppError, now_ms, validate_uuidv7};
use serde::{Deserialize, Serialize};
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions};
use sqlx::{Row, SqlitePool};

use crate::config::MAX_FIELD_CHARS;
use crate::rules::{ActivityRule, ObservationSettings, RuleAction, RuleScope};

/// Current store contract version (`PRAGMA user_version`).
const STORE_VERSION: i64 = 1;

const SCHEMA: &str = r#"
CREATE TABLE IF NOT EXISTS activity_segments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id TEXT NOT NULL UNIQUE,
  user_id TEXT NOT NULL,
  started_at_ms INTEGER NOT NULL,
  ended_at_ms INTEGER NOT NULL,
  app_name TEXT NOT NULL,
  bundle_id TEXT,
  window_title TEXT,
  browser_url TEXT,
  browser_title TEXT,
  source TEXT NOT NULL,
  captured_at_ms INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_activity_segments_user_time
  ON activity_segments(user_id, started_at_ms);
CREATE INDEX IF NOT EXISTS idx_activity_segments_app
  ON activity_segments(user_id, app_name, started_at_ms);
CREATE INDEX IF NOT EXISTS idx_activity_segments_ended
  ON activity_segments(ended_at_ms);

CREATE TABLE IF NOT EXISTS observation_rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rule_id TEXT NOT NULL UNIQUE,
  scope TEXT NOT NULL,
  bundle_id TEXT,
  url_domain TEXT,
  action TEXT NOT NULL,
  list_kind TEXT NOT NULL,
  created_at_ms INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_observation_rules_scope
  ON observation_rules(list_kind, scope);

CREATE TABLE IF NOT EXISTS feature_config (
  config_key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at_ms INTEGER NOT NULL
);
"#;

/// Tables that make up the exact baseline contract.
const BASELINE_TABLES: &[&str] = &["activity_segments", "feature_config", "observation_rules"];

fn db_err(e: sqlx::Error) -> AppError {
    AppError::Internal(format!("computer history store: {e}"))
}

fn truncate_field(value: &str) -> String {
    if value.chars().count() <= MAX_FIELD_CHARS {
        return value.to_string();
    }
    value.chars().take(MAX_FIELD_CHARS).collect()
}

/// One persisted activity segment: contiguous focus on the same
/// (app, window title, browser URL) triple. One row per focus switch, not per
/// poll — the observer's dedup state machine merges identical consecutive
/// samples by extending `ended_at_ms`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActivitySegment {
    /// Bare UUIDv7, generated by the observer when a segment opens.
    pub event_id: String,
    /// Canonical UUIDv7 owner.
    pub user_id: String,
    pub started_at_ms: i64,
    pub ended_at_ms: i64,
    pub app_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bundle_id: Option<String>,
    /// Redacted before persistence.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window_title: Option<String>,
    /// Only present when URL capture is enabled for the focused browser.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub browser_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub browser_title: Option<String>,
    /// `foreground` (app focus change) or `browser` (URL/title within a
    /// browser window).
    pub source: String,
    pub captured_at_ms: i64,
}

/// Time-window + optional filters for read paths.
#[derive(Debug, Clone, Default)]
pub struct SegmentFilter {
    pub from_ms: Option<i64>,
    pub to_ms: Option<i64>,
    pub app_name: Option<String>,
    pub url_contains: Option<String>,
    pub limit: u32,
}

impl SegmentFilter {
    fn limit(&self) -> u32 {
        if self.limit == 0 {
            50
        } else {
            self.limit
        }
    }
}

/// Aggregated foreground time per app.
#[derive(Debug, Clone, Serialize)]
pub struct AppUsageRow {
    pub app_name: String,
    pub total_ms: i64,
    pub segment_count: i64,
}

/// Aggregated browsing time per URL.
#[derive(Debug, Clone, Serialize)]
pub struct UrlRow {
    pub browser_url: String,
    pub browser_title: Option<String>,
    pub total_ms: i64,
    pub segment_count: i64,
}

/// Storage usage snapshot for status surfaces.
#[derive(Debug, Clone, Serialize)]
pub struct StorageStatus {
    pub segment_count: u64,
    pub db_bytes: u64,
    pub segments_dir_bytes: u64,
    pub oldest_started_at_ms: Option<i64>,
    pub newest_ended_at_ms: Option<i64>,
    pub retention_days: u32,
}

pub struct ActivityStore {
    pool: SqlitePool,
    db_path: Option<std::path::PathBuf>,
    segments_dir: Option<std::path::PathBuf>,
}

impl ActivityStore {
    /// Open (or create) the feature-local `{dir}/history.db` and the raw
    /// event-stream root `{dir}/segments/`.
    pub async fn open(dir: &Path) -> Result<Self, AppError> {
        std::fs::create_dir_all(dir)
            .map_err(|e| AppError::Internal(format!("create computer-history dir: {e}")))?;
        let database_path = dir.join("history.db");
        let database_exists = match std::fs::symlink_metadata(&database_path) {
            Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
                return Err(AppError::Internal(format!(
                    "computer-history store path is not a regular file: {}",
                    database_path.display()
                )));
            }
            Ok(_) => true,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => false,
            Err(error) => {
                return Err(AppError::Internal(format!(
                    "inspect computer-history store {}: {error}",
                    database_path.display()
                )));
            }
        };
        let opts = SqliteConnectOptions::new()
            .filename(&database_path)
            .create_if_missing(!database_exists)
            .journal_mode(SqliteJournalMode::Wal)
            .busy_timeout(std::time::Duration::from_secs(5));
        {
            let bootstrap = SqlitePoolOptions::new()
                .max_connections(1)
                .connect_with(opts.clone())
                .await
                .map_err(db_err)?;
            let init = if database_exists {
                validate_baseline_schema(&bootstrap).await
            } else {
                create_baseline_schema(&bootstrap).await
            };
            bootstrap.close().await;
            init?;
        }
        let pool = SqlitePoolOptions::new()
            .max_connections(3)
            .connect_with(opts)
            .await
            .map_err(db_err)?;
        validate_baseline_schema(&pool).await?;
        let segments_dir = dir.join("segments");
        std::fs::create_dir_all(&segments_dir)
            .map_err(|e| AppError::Internal(format!("create segments dir: {e}")))?;
        Ok(Self {
            pool,
            db_path: Some(database_path),
            segments_dir: Some(segments_dir),
        })
    }

    /// In-memory store for tests. The db lives inside the pool's single
    /// connection, so schema bootstrap must run on that same pool.
    pub async fn open_memory() -> Result<Self, AppError> {
        let opts = SqliteConnectOptions::new().in_memory(true);
        let pool = SqlitePoolOptions::new()
            .max_connections(1)
            .connect_with(opts)
            .await
            .map_err(db_err)?;
        create_baseline_schema(&pool).await?;
        Ok(Self {
            pool,
            db_path: None,
            segments_dir: None,
        })
    }

    /// Append completed segments in one transaction. Inputs are trusted to
    /// have been redacted by the observer; fields are still truncated here as
    /// defense in depth.
    pub async fn append_segments(&self, segments: &[ActivitySegment]) -> Result<(), AppError> {
        if segments.is_empty() {
            return Ok(());
        }
        let mut tx = self.pool.begin().await.map_err(db_err)?;
        for segment in segments {
            validate_uuidv7(&segment.event_id)
                .map_err(|e| AppError::BadRequest(format!("segment event_id: {e}")))?;
            validate_uuidv7(&segment.user_id)
                .map_err(|e| AppError::BadRequest(format!("segment user_id: {e}")))?;
            sqlx::query(
                "INSERT INTO activity_segments(\
                   event_id, user_id, started_at_ms, ended_at_ms, app_name, bundle_id, \
                   window_title, browser_url, browser_title, source, captured_at_ms\
                 ) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            )
            .bind(&segment.event_id)
            .bind(&segment.user_id)
            .bind(segment.started_at_ms)
            .bind(segment.ended_at_ms)
            .bind(truncate_field(&segment.app_name))
            .bind(segment.bundle_id.as_deref().map(truncate_field))
            .bind(segment.window_title.as_deref().map(truncate_field))
            .bind(segment.browser_url.as_deref().map(truncate_field))
            .bind(segment.browser_title.as_deref().map(truncate_field))
            .bind(&segment.source)
            .bind(segment.captured_at_ms)
            .execute(&mut *tx)
            .await
            .map_err(db_err)?;
        }
        tx.commit().await.map_err(db_err)
    }

    /// Extend (or close) the open segment identified by `event_id`.
    pub async fn close_open_segment(
        &self,
        event_id: &str,
        ended_at_ms: i64,
    ) -> Result<(), AppError> {
        sqlx::query("UPDATE activity_segments SET ended_at_ms = ? WHERE event_id = ?")
            .bind(ended_at_ms)
            .bind(event_id)
            .execute(&self.pool)
            .await
            .map_err(db_err)?;
        Ok(())
    }

    /// Segments overlapping the filter window, newest first.
    pub async fn query_segments(
        &self,
        filter: &SegmentFilter,
    ) -> Result<Vec<ActivitySegment>, AppError> {
        let mut sql = String::from(
            "SELECT event_id, user_id, started_at_ms, ended_at_ms, app_name, bundle_id, \
             window_title, browser_url, browser_title, source, captured_at_ms \
             FROM activity_segments WHERE 1=1",
        );
        let mut binds: Vec<String> = Vec::new();
        if let Some(from) = filter.from_ms {
            sql.push_str(" AND ended_at_ms >= ?");
            binds.push(from.to_string());
        }
        if let Some(to) = filter.to_ms {
            sql.push_str(" AND started_at_ms < ?");
            binds.push(to.to_string());
        }
        if let Some(app) = &filter.app_name {
            sql.push_str(" AND app_name = ?");
            binds.push(app.clone());
        }
        if let Some(url) = &filter.url_contains {
            sql.push_str(" AND browser_url LIKE ?");
            binds.push(format!("%{url}%"));
        }
        sql.push_str(" ORDER BY started_at_ms DESC LIMIT ?");
        binds.push(filter.limit().to_string());

        let mut query = sqlx::query(&sql);
        for bind in &binds {
            query = query.bind(bind);
        }
        let rows = query.fetch_all(&self.pool).await.map_err(db_err)?;
        Ok(rows.into_iter().map(segment_from_row).collect())
    }

    /// Foreground time per app inside the filter window.
    pub async fn app_usage(&self, filter: &SegmentFilter) -> Result<Vec<AppUsageRow>, AppError> {
        let mut sql = String::from(
            "SELECT app_name, SUM(ended_at_ms - started_at_ms) AS total_ms, COUNT(*) AS segment_count \
             FROM activity_segments WHERE 1=1",
        );
        let mut binds: Vec<String> = Vec::new();
        if let Some(from) = filter.from_ms {
            sql.push_str(" AND ended_at_ms >= ?");
            binds.push(from.to_string());
        }
        if let Some(to) = filter.to_ms {
            sql.push_str(" AND started_at_ms < ?");
            binds.push(to.to_string());
        }
        sql.push_str(" GROUP BY app_name ORDER BY total_ms DESC LIMIT ?");
        binds.push(filter.limit().to_string());

        let mut query = sqlx::query(&sql);
        for bind in &binds {
            query = query.bind(bind);
        }
        let rows = query.fetch_all(&self.pool).await.map_err(db_err)?;
        Ok(rows
            .into_iter()
            .map(|row| AppUsageRow {
                app_name: row.get("app_name"),
                total_ms: row.get::<i64, _>("total_ms"),
                segment_count: row.get::<i64, _>("segment_count"),
            })
            .collect())
    }

    /// Browsing time per URL inside the filter window (rows without a URL are
    /// skipped).
    pub async fn url_history(&self, filter: &SegmentFilter) -> Result<Vec<UrlRow>, AppError> {
        let mut sql = String::from(
            "SELECT browser_url, browser_title, SUM(ended_at_ms - started_at_ms) AS total_ms, COUNT(*) AS segment_count \
             FROM activity_segments WHERE browser_url IS NOT NULL AND browser_url != ''",
        );
        let mut binds: Vec<String> = Vec::new();
        if let Some(from) = filter.from_ms {
            sql.push_str(" AND ended_at_ms >= ?");
            binds.push(from.to_string());
        }
        if let Some(to) = filter.to_ms {
            sql.push_str(" AND started_at_ms < ?");
            binds.push(to.to_string());
        }
        if let Some(url) = &filter.url_contains {
            sql.push_str(" AND browser_url LIKE ?");
            binds.push(format!("%{url}%"));
        }
        sql.push_str(" GROUP BY browser_url ORDER BY total_ms DESC LIMIT ?");
        binds.push(filter.limit().to_string());

        let mut query = sqlx::query(&sql);
        for bind in &binds {
            query = query.bind(bind);
        }
        let rows = query.fetch_all(&self.pool).await.map_err(db_err)?;
        Ok(rows
            .into_iter()
            .map(|row| UrlRow {
                browser_url: row.get("browser_url"),
                browser_title: row.get("browser_title"),
                total_ms: row.get::<i64, _>("total_ms"),
                segment_count: row.get::<i64, _>("segment_count"),
            })
            .collect())
    }

    /// Delete segments that ended before `ts_ms`; returns the row count.
    pub async fn purge_before(&self, ts_ms: i64) -> Result<u64, AppError> {
        let result = sqlx::query("DELETE FROM activity_segments WHERE ended_at_ms < ?")
            .bind(ts_ms)
            .execute(&self.pool)
            .await
            .map_err(db_err)?;
        Ok(result.rows_affected())
    }

    /// Purge the whole activity history (clear-history scope `all`).
    pub async fn purge_all(&self) -> Result<u64, AppError> {
        let result = sqlx::query("DELETE FROM activity_segments")
            .execute(&self.pool)
            .await
            .map_err(db_err)?;
        Ok(result.rows_affected())
    }

    /// Delete segments whose `ended_at_ms` falls inside `[from_ms, to_ms]`.
    pub async fn purge_ended_between(
        &self,
        from_ms: i64,
        to_ms: i64,
    ) -> Result<u64, AppError> {
        let result = sqlx::query(
            "DELETE FROM activity_segments WHERE ended_at_ms BETWEEN ? AND ?",
        )
        .bind(from_ms)
        .bind(to_ms)
        .execute(&self.pool)
        .await
        .map_err(db_err)?;
        Ok(result.rows_affected())
    }

    pub async fn storage_status(&self, retention_days: u32) -> Result<StorageStatus, AppError> {
        let segment_count: i64 =
            sqlx::query_scalar("SELECT COUNT(*) FROM activity_segments")
                .fetch_one(&self.pool)
                .await
                .map_err(db_err)?;
        let bounds: (Option<i64>, Option<i64>) = sqlx::query_as(
            "SELECT MIN(started_at_ms), MAX(ended_at_ms) FROM activity_segments",
        )
        .fetch_one(&self.pool)
        .await
        .map_err(db_err)?;
        let db_bytes = self
            .db_path
            .as_deref()
            .and_then(|path| std::fs::metadata(path).ok())
            .map(|m| m.len())
            .unwrap_or(0);
        let segments_dir_bytes = dir_size(self.segments_dir.as_deref());
        Ok(StorageStatus {
            segment_count: segment_count.max(0) as u64,
            db_bytes,
            segments_dir_bytes,
            oldest_started_at_ms: bounds.0,
            newest_ended_at_ms: bounds.1,
            retention_days,
        })
    }

    // ----- feature_config KV (settings live here, not in the main DB) -----

    pub async fn get_config(&self, key: &str) -> Result<Option<String>, AppError> {
        let row =
            sqlx::query("SELECT value FROM feature_config WHERE config_key = ?")
                .bind(key)
                .fetch_optional(&self.pool)
                .await
                .map_err(db_err)?;
        Ok(row.map(|r| r.get::<String, _>("value")))
    }

    pub async fn set_config(&self, key: &str, value: &str) -> Result<(), AppError> {
        sqlx::query(
            "INSERT INTO feature_config(config_key, value, updated_at_ms) VALUES(?, ?, ?) \
             ON CONFLICT(config_key) DO UPDATE SET value = excluded.value, updated_at_ms = excluded.updated_at_ms",
        )
        .bind(key)
        .bind(value)
        .bind(now_ms())
        .execute(&self.pool)
        .await
        .map_err(db_err)?;
        Ok(())
    }

    // ----- observation settings + rules -----

    /// Load the full observation settings object (defaults when never saved).
    pub async fn observation_settings(&self) -> Result<ObservationSettings, AppError> {
        let raw = self.get_config(CONFIG_KEY_OBSERVATION).await?;
        match raw {
            Some(raw) => serde_json::from_str(&raw).map_err(|error| {
                AppError::Internal(format!(
                    "computer history stored observation settings are invalid: {error}"
                ))
            }),
            None => Ok(ObservationSettings::default()),
        }
    }

    /// Replace the whole observation settings object (Codex `update_settings`
    /// semantics: full replace, callers fetch first).
    pub async fn set_observation_settings(
        &self,
        settings: &ObservationSettings,
    ) -> Result<(), AppError> {
        let validated = settings.clone().validated()?;
        let raw = serde_json::to_string(&validated)
            .map_err(|e| AppError::Internal(format!("serialize observation settings: {e}")))?;
        self.set_config(CONFIG_KEY_OBSERVATION, &raw).await
    }

    /// Load user rules as structured rows (rule tables follow the same v3
    /// conventions as `activity_segments`).
    pub async fn list_rules(&self) -> Result<Vec<StoredRule>, AppError> {
        let rows = sqlx::query(
            "SELECT rule_id, scope, bundle_id, url_domain, action, list_kind \
             FROM observation_rules ORDER BY rule_id",
        )
        .fetch_all(&self.pool)
        .await
        .map_err(db_err)?;
        Ok(rows
            .into_iter()
            .map(|row| StoredRule {
                rule: ActivityRule {
                    id: row.get("rule_id"),
                    scope: parse_scope(&row.get::<String, _>("scope")),
                    bundle_id: row.get("bundle_id"),
                    url_domain: row.get("url_domain"),
                    action: parse_action(&row.get::<String, _>("action")),
                },
                list_kind: row.get("list_kind"),
            })
            .collect())
    }

    /// Insert or replace one rule row.
    pub async fn upsert_rule(&self, rule: &ActivityRule, list_kind: &str) -> Result<(), AppError> {
        let rule = rule.clone().validated()?;
        sqlx::query(
            "INSERT INTO observation_rules(rule_id, scope, bundle_id, url_domain, action, list_kind, created_at_ms) \
             VALUES(?, ?, ?, ?, ?, ?, ?) \
             ON CONFLICT(rule_id) DO UPDATE SET scope = excluded.scope, bundle_id = excluded.bundle_id, \
             url_domain = excluded.url_domain, action = excluded.action, list_kind = excluded.list_kind",
        )
        .bind(&rule.id)
        .bind(scope_wire(rule.scope))
        .bind(rule.bundle_id)
        .bind(rule.url_domain)
        .bind(action_wire(rule.action))
        .bind(list_kind)
        .bind(now_ms())
        .execute(&self.pool)
        .await
        .map_err(db_err)?;
        Ok(())
    }

    pub async fn delete_rule(&self, rule_id: &str) -> Result<bool, AppError> {
        let result = sqlx::query("DELETE FROM observation_rules WHERE rule_id = ?")
            .bind(rule_id)
            .execute(&self.pool)
            .await
            .map_err(db_err)?;
        Ok(result.rows_affected() > 0)
    }
}

/// Extra rule metadata kept in the rules table (which list the rule belongs
/// to).
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct StoredRule {
    pub rule: ActivityRule,
    pub list_kind: String,
}

/// KV key holding the serialized [`ObservationSettings`] object.
pub const CONFIG_KEY_OBSERVATION: &str = "observation.settings";
/// Master switch (Codex `skysight` toggle). Lives in the feature-local KV so
/// the toggle survives restarts without touching the main DB.
pub const CONFIG_KEY_ENABLED: &str = "enabled";
/// KV key holding the persisted pause deadline (epoch-ms, empty = not paused).
/// Analog of the Codex `skysight.pauseResumeDate` default.
pub const CONFIG_KEY_PAUSE_UNTIL: &str = "pause.until_ms";

fn segment_from_row(row: sqlx::sqlite::SqliteRow) -> ActivitySegment {
    ActivitySegment {
        event_id: row.get("event_id"),
        user_id: row.get("user_id"),
        started_at_ms: row.get("started_at_ms"),
        ended_at_ms: row.get("ended_at_ms"),
        app_name: row.get("app_name"),
        bundle_id: row.get("bundle_id"),
        window_title: row.get("window_title"),
        browser_url: row.get("browser_url"),
        browser_title: row.get("browser_title"),
        source: row.get("source"),
        captured_at_ms: row.get("captured_at_ms"),
    }
}

fn scope_wire(scope: RuleScope) -> &'static str {
    match scope {
        RuleScope::Application => "application",
        RuleScope::Url => "url",
    }
}

fn parse_scope(raw: &str) -> RuleScope {
    if raw == "url" {
        RuleScope::Url
    } else {
        RuleScope::Application
    }
}

fn action_wire(action: RuleAction) -> &'static str {
    match action {
        RuleAction::Capture => "capture",
        RuleAction::Ignore => "ignore",
        RuleAction::Redact => "redact",
    }
}

fn parse_action(raw: &str) -> RuleAction {
    match raw {
        "ignore" => RuleAction::Ignore,
        "redact" => RuleAction::Redact,
        _ => RuleAction::Capture,
    }
}

fn dir_size(path: Option<&std::path::Path>) -> u64 {
    let Some(path) = path else {
        return 0;
    };
    let mut total = 0;
    if let Ok(entries) = std::fs::read_dir(path) {
        for entry in entries.flatten() {
            if let Ok(metadata) = entry.metadata() {
                if metadata.is_file() {
                    total += metadata.len();
                } else if metadata.is_dir() {
                    total += dir_size(Some(&entry.path()));
                }
            }
        }
    }
    total
}

async fn create_baseline_schema(pool: &SqlitePool) -> Result<(), AppError> {
    sqlx::raw_sql(SCHEMA).execute(pool).await.map_err(db_err)?;
    sqlx::raw_sql(&format!("PRAGMA user_version = {STORE_VERSION}"))
        .execute(pool)
        .await
        .map_err(db_err)?;
    validate_baseline_schema(pool).await
}

async fn validate_baseline_schema(pool: &SqlitePool) -> Result<(), AppError> {
    let version: i64 = sqlx::query_scalar("PRAGMA user_version")
        .fetch_one(pool)
        .await
        .map_err(db_err)?;
    if version != STORE_VERSION {
        return Err(AppError::Internal(format!(
            "computer history store contract version mismatch: expected {STORE_VERSION}, found {version}"
        )));
    }
    for table in BASELINE_TABLES {
        let sql: String = sqlx::query_scalar(
            "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?",
        )
        .bind(table)
        .fetch_optional(pool)
        .await
        .map_err(db_err)?
        .ok_or_else(|| {
            AppError::Internal(format!("computer history store missing table {table}"))
        })?;
        // v3 contract: row tables use AUTOINCREMENT ids, nothing declares a
        // physical foreign key (feature_config is a KV table keyed by TEXT).
        if *table != "feature_config" && !sql.contains("INTEGER PRIMARY KEY AUTOINCREMENT") {
            return Err(AppError::Internal(format!(
                "computer history store table {table} must use INTEGER PRIMARY KEY AUTOINCREMENT"
            )));
        }
        let upper = sql.to_ascii_uppercase();
        if upper.contains("REFERENCES") || upper.contains("FOREIGN KEY") {
            return Err(AppError::Internal(format!(
                "computer history store table {table} must not declare physical foreign keys"
            )));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules::DefaultBehavior;

    fn segment(event_id: &str, app: &str, start: i64, end: i64) -> ActivitySegment {
        ActivitySegment {
            event_id: event_id.into(),
            user_id: "01900000-0000-7000-8000-000000000001".into(),
            started_at_ms: start,
            ended_at_ms: end,
            app_name: app.into(),
            bundle_id: Some("com.example.app".into()),
            window_title: Some("token: supersecretvalue123".into()),
            browser_url: Some("https://example.com/docs".into()),
            browser_title: Some("Docs".into()),
            source: "foreground".into(),
            captured_at_ms: end,
        }
    }

    async fn memory_store() -> ActivityStore {
        ActivityStore::open_memory().await.unwrap()
    }

    #[test]
    fn user_id_is_valid_uuidv7() {
        // Sanity for the fixture ids used across tests in this crate.
        validate_uuidv7("01900000-0000-7000-8000-000000000001").unwrap();
    }

    #[tokio::test]
    async fn append_query_and_aggregate() {
        let store = memory_store().await;
        store
            .append_segments(&[
                segment(nomifun_common::generate_id().as_str(), "Safari", 100, 200),
                segment(nomifun_common::generate_id().as_str(), "Safari", 300, 500),
                segment(nomifun_common::generate_id().as_str(), "Terminal", 600, 700),
            ])
            .await
            .unwrap();

        let all = store
            .query_segments(&SegmentFilter {
                limit: 10,
                ..Default::default()
            })
            .await
            .unwrap();
        assert_eq!(all.len(), 3);
        assert_eq!(all[0].app_name, "Terminal"); // newest first

        let usage = store
            .app_usage(&SegmentFilter {
                limit: 10,
                ..Default::default()
            })
            .await
            .unwrap();
        assert_eq!(usage[0].app_name, "Safari");
        assert_eq!(usage[0].total_ms, 300);

        let urls = store
            .url_history(&SegmentFilter::default())
            .await
            .unwrap();
        // All three segments share the same URL, so they group into one row.
        assert_eq!(urls.len(), 1);
        assert_eq!(urls[0].browser_url, "https://example.com/docs");
        assert_eq!(urls[0].total_ms, 400);
    }

    #[tokio::test]
    async fn duplicate_event_id_is_rejected() {
        let store = memory_store().await;
        let dup = "01900000-0000-7000-8000-000000000009";
        store
            .append_segments(&[segment(dup, "Safari", 1, 2)])
            .await
            .unwrap();
        assert!(store.append_segments(&[segment(dup, "Safari", 3, 4)]).await.is_err());
    }

    #[tokio::test]
    async fn close_open_segment_extends_end() {
        let store = memory_store().await;
        let id = nomifun_common::generate_id().to_string();
        store
            .append_segments(&[segment(&id, "Safari", 100, 150)])
            .await
            .unwrap();
        store.close_open_segment(&id, 250).await.unwrap();
        let rows = store.query_segments(&SegmentFilter::default()).await.unwrap();
        assert_eq!(rows[0].ended_at_ms, 250);
    }

    #[tokio::test]
    async fn purge_before_respects_window() {
        let store = memory_store().await;
        store
            .append_segments(&[
                segment(nomifun_common::generate_id().as_str(), "A", 100, 200),
                segment(nomifun_common::generate_id().as_str(), "B", 100, 900),
            ])
            .await
            .unwrap();
        let removed = store.purge_before(500).await.unwrap();
        assert_eq!(removed, 1);
        assert_eq!(store.query_segments(&SegmentFilter::default()).await.unwrap().len(), 1);
    }

    #[tokio::test]
    async fn config_kv_roundtrip_and_upsert() {
        let store = memory_store().await;
        assert_eq!(store.get_config("enabled").await.unwrap(), None);
        store.set_config("enabled", "false").await.unwrap();
        store.set_config("enabled", "true").await.unwrap();
        assert_eq!(store.get_config("enabled").await.unwrap().as_deref(), Some("true"));
    }

    #[tokio::test]
    async fn observation_settings_default_and_replace() {
        let store = memory_store().await;
        assert_eq!(
            store.observation_settings().await.unwrap(),
            ObservationSettings::default()
        );
        let mut settings = ObservationSettings::default();
        settings.default_url_behavior = DefaultBehavior::DoNotObserve;
        settings.blocklist.push(
            ActivityRule {
                id: nomifun_common::generate_id(),
                scope: RuleScope::Application,
                bundle_id: Some("com.example.app".into()),
                url_domain: None,
                action: RuleAction::Ignore,
            }
            .validated()
            .unwrap(),
        );
        store.set_observation_settings(&settings).await.unwrap();
        assert_eq!(store.observation_settings().await.unwrap(), settings);
    }

    #[tokio::test]
    async fn rules_upsert_list_delete() {
        let store = memory_store().await;
        let rule = ActivityRule {
            id: nomifun_common::generate_id(),
            scope: RuleScope::Url,
            bundle_id: None,
            url_domain: Some("example.com".into()),
            action: RuleAction::Capture,
        };
        store.upsert_rule(&rule, "allowlist").await.unwrap();
        store.upsert_rule(&rule, "blocklist").await.unwrap(); // replaces list_kind
        let rules = store.list_rules().await.unwrap();
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].list_kind, "blocklist");
        assert!(store.delete_rule(rule.id.as_str()).await.unwrap());
        assert!(store.list_rules().await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn invalid_rule_is_rejected_on_write() {
        let store = memory_store().await;
        let bad = ActivityRule {
            id: nomifun_common::generate_id(),
            scope: RuleScope::Application,
            bundle_id: Some(String::new()),
            url_domain: None,
            action: RuleAction::Capture,
        };
        assert!(store.upsert_rule(&bad, "allowlist").await.is_err());
    }

    #[tokio::test]
    async fn storage_status_reports_counts() {
        let store = memory_store().await;
        store
            .append_segments(&[segment(nomifun_common::generate_id().as_str(), "A", 1, 2)])
            .await
            .unwrap();
        let status = store.storage_status(30).await.unwrap();
        assert_eq!(status.segment_count, 1);
        assert_eq!(status.retention_days, 30);
    }

    #[tokio::test]
    async fn file_store_rejects_symlink_and_validates_contract() {
        let tmp = tempfile::tempdir().unwrap();
        // First open creates the schema.
        ActivityStore::open(tmp.path()).await.unwrap();
        // Second open validates the existing contract.
        ActivityStore::open(tmp.path()).await.unwrap();
        // A symlinked history.db is refused (companion-store hardening).
        let link = tmp.path().join("history.db");
        let target = tmp.path().join("elsewhere.db");
        std::fs::write(&target, b"").unwrap();
        std::fs::remove_file(&link).unwrap();
        #[cfg(unix)]
        std::os::unix::fs::symlink(&target, &link).unwrap();
        let result = ActivityStore::open(tmp.path()).await;
        #[cfg(unix)]
        assert!(result.is_err());
    }
}
