// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";

/**
 * Latest health observation for one task-scoped capability.
 */
export type CapabilityHealth = { status: HealthStatus, latency?: number, error?: string, };
