// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";
import type { ProviderHealthCheckErrorKind } from "./ProviderHealthCheckErrorKind";

/**
 * Latest health observation for one task-scoped capability.
 *
 * The diagnostic fields are all optional so a row written by an older build
 * (`status`/`latency`/`error` only) still deserializes under
 * `deny_unknown_fields`; no migration is needed because the column is opaque
 * JSON.
 */
export type CapabilityHealth = { status: HealthStatus, latency?: number, error?: string,
/**
 * Why it failed, as a machine-readable category. Persisting only `error`
 * meant a 404 and a 401 were indistinguishable once the check was over.
 */
error_kind?: ProviderHealthCheckErrorKind, http_status?: number,
/**
 * The URL that was requested, with query material redacted.
 */
attempted_url?: string, };
