// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A concrete provider/model selection returned by catalog resolution.
 */
export type CatalogModelRef = { provider_id: string, model: string, };
