// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/providers/:id/clone`.
 *
 * The body is optional on the wire: a missing/empty body clones with the
 * default `"{source name} copy"` name.
 */
export type CloneProviderRequest = {
/**
 * Optional display name for the clone. A trimmed non-empty value wins;
 * missing/blank falls back to `"{source name} copy"`.
 */
name?: string | null, };
