// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";
import type { ModelTrait } from "./ModelTrait";

/**
 * Body for `POST /api/provider-models` — create one catalog row.
 *
 * `tasks` left empty means "no explicit profile": the service seeds the
 * heuristic profile ([`crate::derive_tasks_and_traits`]) with
 * `source = inferred`; a non-empty `tasks` is an explicit user profile
 * (`source = user`).
 */
export type CreateProviderModelRequest = { provider_id: string, model: string, enabled?: boolean, tasks?: Array<ModelTask>, traits?: Array<ModelTrait>, protocol?: string, connection_role?: string, params?: unknown, context_limit?: number, description?: string, sort_order?: number, };
