// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which half of a request URL carries the provider's API version segment.
 *
 * The two variants are mutually exclusive, and every HTTP protocol picks one.
 * Nothing in the wire format can infer this: `/chat/completions` and
 * `/v1/messages` are both valid endpoint templates, and the only difference is
 * whether the connection root is expected to end in `/v1` already. Stating it
 * here is what lets a custom provider be told the convention instead of having
 * to guess it — the manifest deliberately withholds `default_connections` from
 * custom-scope providers, but endpoint descriptors always reach them.
 */
export type EndpointRootShape = "versioned_root" | "origin_root";
