// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelCatalogSource } from "./ModelCatalogSource";
import type { ModelInfo } from "./ModelInfo";

/**
 * Response for `POST /api/providers/:id/models`.
 */
export type FetchModelsResponse = { models: Array<ModelInfo>, catalog_source?: ModelCatalogSource, fixed_base_url?: string, };
