// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health status values for a model.
 */
export type HealthStatus = "unknown" | "healthy" | "unhealthy";
