// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeEmbeddingConfig } from "./KnowledgeEmbeddingConfig";
import type { KnowledgeRerankConfig } from "./KnowledgeRerankConfig";

/**
 * Install-wide knowledge retrieval policy persisted under the single
 * `client_preferences` key `knowledge.retrieval`.
 *
 * Both stages default explicitly to `local`; there is no implicit "first
 * available model" lookup and no runtime fallback from a configured remote
 * stage.
 */
export type KnowledgeRetrievalConfig = { embedding: KnowledgeEmbeddingConfig, rerank: KnowledgeRerankConfig, };
