// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result-ordering backend used after knowledge candidates are collected.
 *
 * The stages are independent: local keyword candidates may be remotely
 * reranked, and remote embedding candidates may keep their local cosine
 * order. A configured remote stage is never treated as optional at runtime.
 */
export type KnowledgeRerankConfig = { "mode": "local", } | { "mode": "remote", provider_id: string, model: string, };
