// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeEntrySourceRelationship } from "./KnowledgeEntrySourceRelationship";
import type { KnowledgeSourceSyncStatus } from "./KnowledgeSourceSyncStatus";

/**
 * Source metadata attached to a tree/read DTO.  The stable source-item and
 * entry identities are authoritative; the current path is never used to
 * decide ownership or write access.
 */
export type KnowledgeEntrySourceInfo = { source_id: string, source_item_id: string, source_url: string, relationship: KnowledgeEntrySourceRelationship, sync_status: KnowledgeSourceSyncStatus, final_url?: string, last_success_at?: number, last_error?: string, };
