// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-enforced mutation policy for a filesystem-backed knowledge base.
 * External directories default to read-only and require explicit user consent
 * before the application may edit or restructure them.
 */
export type KnowledgeTreeAccess = "read_only" | "editable";
