// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted per-source-item synchronization state.  `conflicted` means the
 * local managed document changed since the last successful publication and
 * the refresher deliberately refused to overwrite it.
 */
export type KnowledgeSourceSyncStatus = "pending" | "syncing" | "synced" | "failed" | "conflicted" | "missing" | "paused";
