// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance controls product policy (for example, URL snapshots are
 * source-managed even though they appear in the same tree).
 */
export type KnowledgeEntryOrigin = "user" | "url_snapshot" | "generated";
