// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-enforced mutation policy for a filesystem-backed knowledge base.
 * The desktop local-folder flow makes an explicit choice (editable by product
 * default); lower-level API callers that omit a choice retain the conservative
 * external-folder read-only default.
 */
export type KnowledgeTreeAccess = "read_only" | "editable";
