// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Candidate-generation backend used by knowledge retrieval.
 *
 * `local` is the explicit, no-network keyword implementation. `remote`
 * identifies one exact provider model whose `embedding` capability must be
 * enabled at save time and every time it is invoked.
 */
export type KnowledgeEmbeddingConfig = { "mode": "local", } | { "mode": "remote", provider_id: string, model: string, };
