// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The durable relationship between a filesystem entry and a source item.
 *
 * Provenance and edit policy are intentionally separate: a detached or copied
 * web document still came from the web, but its contents are user-owned.
 */
export type KnowledgeEntrySourceRelationship = "managed" | "detached" | "copy";
