// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeEntryKind } from "./KnowledgeEntryKind";
import type { KnowledgeEntryOrigin } from "./KnowledgeEntryOrigin";

/**
 * File/directory identity projected from one knowledge base. `entry_id` is
 * stable across rename/move; `rel_path` is its current filesystem locator.
 */
export type KnowledgeEntry = { entryId: string, knowledgeBaseId: string, parentEntryId: string | null, name: string, kind: KnowledgeEntryKind, origin: KnowledgeEntryOrigin, relPath: string, revision: number, deletedAt: number | null, };
