// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-resolved product capabilities for one entry.  Clients render these
 * flags but every mutation is checked again by the service; neither `origin`
 * nor a directory name is a security boundary.
 */
export type KnowledgeEntryCapabilities = { read_content: boolean, edit_content: boolean, rename: boolean, relocate: boolean, accept_children: boolean, delete_entry: boolean, remove_source: boolean, refresh_source: boolean, detach_source: boolean, copy_as_editable: boolean, export_entry: boolean, edit_metadata: boolean, read_only_reason?: string, };
