// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host-managed technical capability. Every Chat model starts optimistic;
 * only explicit, machine-readable provider evidence records an unsupported
 * capability. Users never author these values.
 */
export type ModelTechnicalCapability = "function_calling" | "reasoning" | "streaming";
