// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelGatewayQuota } from "./ModelGatewayQuota";

export type ModelGatewayPlan = { name: string, period_start: string | null, period_end: string | null, quota: ModelGatewayQuota, };
