// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelGatewayCatalogModel } from "./ModelGatewayCatalogModel";
import type { ProviderModelInput } from "./ProviderModelInput";

export type ModelGatewayCatalogResponse = { contract_version: string, models: Array<ModelGatewayCatalogModel>,
/**
 * Exact validated configuration; no platform or name-based inference.
 */
imports: Array<ProviderModelInput>, };
