// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelGatewayOperator = { name: string, homepage_url: string | null, console_url: string | null, purchase_url: string | null, terms_url: string | null, privacy_url: string | null, };
