// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the offered model IDs came from. Documentation suggestions do not
 * prove account access or that a provider's live catalog was refreshed.
 */
export type ModelCatalogSource = "remote" | "official_documentation";
