// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The endpoint-determining task a model performs. Wire values are snake_case.
 */
export type ModelTask = "chat" | "image_generation" | "image_edit" | "video_generation" | "speech_synthesis" | "speech_recognition" | "embedding" | "rerank";
