// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-declared semantic refinement of a Chat model.
 *
 * Function calling, reasoning and streaming are intentionally absent. They
 * are runtime capabilities, not configuration checkboxes. Realtime is a
 * standalone [`ModelTask::RealtimeConversation`] and must never be duplicated
 * as a Chat trait.
 */
export type ModelTrait = "vision_input" | "web_search" | "audio_input" | "video_input";
