// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelGatewayPrice } from "./ModelGatewayPrice";
import type { ModelGatewayTaskEndpoints } from "./ModelGatewayTaskEndpoints";
import type { ModelTask } from "./ModelTask";

export type ModelGatewayCatalogModel = { id: string, display_name: string, vendor: string, tasks: Array<ModelTask>, task_endpoints: { [key in string]: ModelGatewayTaskEndpoints }, context_window: number | null, max_output_tokens: number | null, input_modalities: Array<string>, traits: Array<string>, pricing: Array<ModelGatewayPrice>, included_in_plan: boolean, status: string, };
