// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";
import type { ModelTaskSource } from "./ModelTaskSource";
import type { ModelTokenLimitSources } from "./ModelTokenLimitSources";
import type { ModelTrait } from "./ModelTrait";

/**
 * A fetched model entry with one fixed wire shape.
 */
export type ModelInfo = { id: string, name: string | null, tasks?: Array<ModelTask>,
/**
 * Absent means unknown, including catalogs produced by an older host.
 * Only explicit provider declarations or exact documented profiles may
 * initialize a task without asking the user to confirm its purpose.
 */
tasks_source?: ModelTaskSource, traits?: Array<ModelTrait>,
/**
 * Input context window the provider's own catalog declared for this model,
 * in tokens. This is the only automatic source for the value a user would
 * otherwise have to type into the chat capability's `context_limit`, so it
 * deliberately reuses that name.
 *
 * Absent — never `null` — when the catalog said nothing, so a client can
 * distinguish "the provider did not declare a window" from a declared
 * value. Only positive values are carried; nothing is inferred from a
 * model id.
 */
context_limit?: number,
/**
 * Provider-declared maximum output tokens. Absent when unknown; this is
 * an import suggestion, never permission to replace an existing manual
 * ceiling or an explicit provider-default (`None`) configuration.
 */
output_limit?: number, token_limit_sources?: ModelTokenLimitSources, };
