// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelGatewayOperator } from "./ModelGatewayOperator";

export type ModelGatewayMetaResponse = { contract_version: string, operator: ModelGatewayOperator, capabilities: Array<string>, optional_endpoints: Array<string>, };
