// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";

/**
 * Per-model health check information.
 */
export type ModelHealthStatus = { status: HealthStatus, last_check?: number, latency?: number, error?: string, };
