// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The task selected by an exact provider-model capability row. Wire values are
 * snake_case.
 */
export type ModelTask = "chat" | "realtime_conversation" | "image_generation" | "image_edit" | "video_generation" | "speech_synthesis" | "speech_recognition" | "embedding" | "rerank";
