// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";

export type ModelGatewayPrice = { task: ModelTask, meter: string, unit_size: string, amount: string, currency: string, };
