// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelGatewayKey = { name: string, expires_at: string | null, quota_unit: string, remaining_quota: string | null, };
