// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthSchemeDescriptor } from "./AuthSchemeDescriptor";
import type { ModelTask } from "./ModelTask";
import type { ProtocolDescriptor } from "./ProtocolDescriptor";
import type { ProtocolRecommendation } from "./ProtocolRecommendation";

export type ModelProtocolManifestResponse = { tasks: Array<ModelTask>, preset: string, platform: string, requested_task: ModelTask, platform_default_base_url: string | null, requires_user_input: boolean, default_auth_scheme: string | null, auth_schemes: Array<AuthSchemeDescriptor>, recommendation: ProtocolRecommendation | null, protocols: Array<ProtocolDescriptor>, };
