// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelGatewayRateLimits = { requests_per_minute: string | null, tokens_per_minute: string | null, concurrent_requests: string | null, };
