// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic dimension of a declared context value. An input ceiling must not
 * have the independently declared output ceiling subtracted from it.
 */
export type ModelContextLimitKind = "input_only" | "combined";
