// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Within-task refinement of a model's abilities. Mostly modifies [`ModelTask::Chat`].
 */
export type ModelTrait = "vision_input" | "function_calling" | "reasoning" | "web_search";
