// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evidence supporting a model catalog's suggested tasks. A live model ID is
 * not itself a task declaration: name-based suggestions remain inferred even
 * when the ID came from a provider's current catalog.
 */
export type ModelTaskSource = "provider_declared" | "official_documentation" | "inferred";
