// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelContextLimitKind } from "./ModelContextLimitKind";

/**
 * Field-level origin of advisory token limits from a provider catalog.
 * These are response field paths, not inferred limits or user preferences.
 */
export type ModelTokenLimitSources = { context_limit?: string, output_limit?: string, context_limit_kind?: ModelContextLimitKind, };
