// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelGatewayBalance } from "./ModelGatewayBalance";
import type { ModelGatewayKey } from "./ModelGatewayKey";
import type { ModelGatewayPlan } from "./ModelGatewayPlan";
import type { ModelGatewayRateLimits } from "./ModelGatewayRateLimits";

export type ModelGatewayAccountResponse = { contract_version: string, plan: ModelGatewayPlan | null, balance: ModelGatewayBalance, key: ModelGatewayKey, rate_limits: ModelGatewayRateLimits, };
