// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `OutputDiscarded` event.
 */
export type OutputDiscardedEventData = {
/**
 * One-based round attempt that will produce the replacement output.
 */
restart_attempt: number, };
