// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlatformPresetDescriptor = { preset: string, platform: string, platform_default_base_url: string | null, requires_user_input: boolean, default_auth_scheme: string | null, };
