// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointRootShape } from "./EndpointRootShape";
import type { ModelTask } from "./ModelTask";
import type { ProbeCandidateResult } from "./ProbeCandidateResult";
import type { ProviderHealthCheckErrorKind } from "./ProviderHealthCheckErrorKind";
import type { ProviderReachability } from "./ProviderReachability";

/**
 * Response for both probe-connection routes.
 */
export type ProbeProviderConnectionResponse = { reachability: ProviderReachability, protocol: string, task: ModelTask,
/**
 * Which half of the URL the chosen protocol expects to carry the version.
 */
root_shape: EndpointRootShape,
/**
 * The exact URL requested, with query material redacted.
 */
attempted_url: string, http_status?: number, error_kind?: ProviderHealthCheckErrorKind, content_type?: string, message?: string, elapsed_ms: number,
/**
 * A root that answered better than the configured one, offered for one-click
 * adoption. This is what the previously-discarded `fixed_base_url` should
 * always have been.
 */
suggested_base_url?: string, candidates?: Array<ProbeCandidateResult>, };
