// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";

/**
 * Request body for `POST /api/providers/{provider_id}/probe-connection`.
 */
export type ProbeProviderConnectionRequest = { 
/**
 * Protocol whose endpoint template defines the path to probe. Required for
 * custom providers, which get no recommendation to fall back on.
 */
protocol?: string, task?: ModelTask, 
/**
 * Probe alternative roots when the configured one is unreachable.
 */
probe_candidates: boolean, };
