// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";

/**
 * Request body for `POST /api/providers/probe-connection` (anonymous).
 */
export type ProbeProviderConnectionAnonymousRequest = { platform: string, base_url: string, auth_scheme: string, credentials: unknown, protocol?: string, task?: ModelTask, probe_candidates: boolean, };
