// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderReachability } from "./ProviderReachability";

/**
 * One candidate root's probe outcome, in deterministic probe order.
 */
export type ProbeCandidateResult = { base_url: string, attempted_url: string, reachability: ProviderReachability, http_status?: number, content_type?: string, };
