// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance of a [`ModelProfile`]. User-authored profiles override inferred values.
 */
export type ProfileSource = "inferred" | "user";
