// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";
import type { ProtocolEndpointDescriptor } from "./ProtocolEndpointDescriptor";
import type { ProtocolExecutorKind } from "./ProtocolExecutorKind";
import type { ProtocolTransportKind } from "./ProtocolTransportKind";

export type ProtocolTaskDescriptor = { protocol_id: string, task: ModelTask, executor: ProtocolExecutorKind, transport: ProtocolTransportKind, endpoints: Array<ProtocolEndpointDescriptor>, };
