// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProtocolRecommendation = { protocol_id: string, connection_role: string | null, default_base_url: string | null, default_auth_scheme: string | null, base_url_override_required: boolean, };
