// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProtocolDefaultConnection = { preset: string, platform: string, connection_role: string | null, connection_label: string | null, base_url: string, auth_scheme: string, requires_credentials: boolean, };
