// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointRootShape } from "./EndpointRootShape";
import type { ModelTask } from "./ModelTask";
import type { ProtocolEndpointPurpose } from "./ProtocolEndpointPurpose";

export type ProtocolEndpointDescriptor = { task: ModelTask, field: string, purpose: ProtocolEndpointPurpose, method: string | null, default_value: string,
/**
 * Which half of the URL owns the version segment for this endpoint.
 */
root_shape: EndpointRootShape,
/**
 * The complete placeholder vocabulary accepted by this protocol field.
 */
allowed_placeholders: Array<string>,
/**
 * Alternatives of which at least one must occur in every configured
 * override. Poll/content job identifiers are required; submit/session
 * model placeholders remain optional so an exact model URL is valid.
 */
required_placeholders: Array<string>, editable: boolean, };
