// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointRootShape } from "./EndpointRootShape";
import type { ModelTask } from "./ModelTask";
import type { ProtocolDefaultConnection } from "./ProtocolDefaultConnection";
import type { ProtocolEndpointDescriptor } from "./ProtocolEndpointDescriptor";
import type { ProtocolExecutorKind } from "./ProtocolExecutorKind";
import type { ProtocolScope } from "./ProtocolScope";
import type { ProtocolTransportKind } from "./ProtocolTransportKind";

export type ProtocolDescriptor = { protocol_id: string, supported_tasks: Array<ModelTask>, executor: ProtocolExecutorKind, transport: ProtocolTransportKind, 
/**
 * Whether this protocol's request body requires an explicit output limit.
 */
requires_output_ceiling: boolean,
/**
 * Persisted auth schemes accepted by this protocol executor. Parameterized
 * generic transports use `header_key:<name>` / `query_key:<param>` as
 * wildcard vocabulary; Agent protocols list their exact required scheme.
 */
allowed_auth_schemes: Array<string>, scopes: Array<ProtocolScope>, platforms: Array<string>, default_connections: Array<ProtocolDefaultConnection>, endpoints: Array<ProtocolEndpointDescriptor>, 
/**
 * The shape shared by every endpoint of this protocol. `None` for `sdk`
 * transports, which build no URL at all.
 */
root_shape: EndpointRootShape | null, };
