// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How conclusively a connection root answered a reachability probe.
 *
 * The three-state result exists because a binary pass/fail cannot express the
 * most common real situation: the address is correct and the credential is not.
 * A 401/403 proves an endpoint exists and is enforcing auth, so it confirms the
 * URL even though the request failed.
 */
export type ProviderReachability = "reachable" | "credentials_rejected" | "unreachable";
