// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response never echoes credentials back; `has_credentials` signals presence.
 */
export type ProviderConnectionResponse = { connection_id: string, provider_id: string, role: string, label?: string, base_url: string, auth_scheme: string, has_credentials: boolean, is_full_url: boolean, extra: unknown, created_at: number, updated_at: number, };
