// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse failure category for provider/model health checks.
 */
export type ProviderHealthCheckErrorKind = "timeout" | "invalid_authorization_header" | "unauthorized" | "forbidden" | "not_found" | "model_unavailable" | "insufficient_quota" | "aws_credentials" | "invalid_request" | "rate_limited" | "connection_error" | "api_error" | "non_api_response" | "unknown";
