// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";
import type { ModelTrait } from "./ModelTrait";

/**
 * Complete user-authored configuration for one model modality.
 *
 * `protocol` and `connection_role` are intentionally required and nonblank.
 * Even the default provider connection is represented explicitly as
 * `connection_role = "default"`; there is no implicit or legacy fallback.
 */
export type ProviderModelCapabilityInput = { task: ModelTask, traits?: Array<ModelTrait>, protocol: string, connection_role: string, base_url_override?: string, endpoint?: string, poll_endpoint?: string, content_endpoint?: string, realtime_endpoint?: string, allow_cross_origin_credentials?: boolean, provider_params?: unknown, context_limit?: number, };
