// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderModelCapabilityInput } from "./ProviderModelCapabilityInput";

/**
 * Complete provider-model input reused by aggregate provider creation and
 * the standalone full-save endpoint. It deliberately has no provider id.
 */
export type ProviderModelInput = { model: string,
/**
 * Generic human-readable label; invocation always uses `model`.
 */
display_name?: string, enabled?: boolean, description?: string, sort_order?: number, capabilities: Array<ProviderModelCapabilityInput>, };
