// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Named connection input nested in aggregate provider creation. Every child
 * row is new, so its typed credential payload is explicit. Authentication
 * schemes such as SDK default-chain may use an empty object, but the field is
 * never omitted.
 */
export type ProviderConnectionInput = { role: string, label?: string | null, base_url: string, auth_scheme: string,
/**
 * Write-only structured credentials (shape depends on `auth_scheme`). Key
 * schemes use `{ "api_keys": ["..."] }`. Values are encrypted at rest.
 */
credentials: unknown, extra?: unknown, };
