// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";
import type { ModelTask } from "./ModelTask";
import type { ProviderHealthCheckErrorKind } from "./ProviderHealthCheckErrorKind";

/**
 * Response body for `POST /api/agents/provider-health-check`.
 */
export type ProviderHealthCheckResponse = { provider_id: string, platform: string, model: string, task: ModelTask, status: HealthStatus, elapsed_ms: number, message?: string, error_kind?: ProviderHealthCheckErrorKind, http_status?: number, timeout_stage?: string, 
/**
 * The URL this check actually requested, with query material redacted.
 *
 * Without it a wrong base URL and a rejected key are indistinguishable in
 * the UI: both render as a failure with upstream prose and no address.
 */
attempted_url?: string, };
