// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";

/**
 * Request body for `POST /api/agents/provider-health-check`.
 */
export type ProviderHealthCheckRequest = { provider_id: string, model: string,
/**
 * Exact persisted capability to probe. There is no primary-task or chat
 * fallback.
 */
task: ModelTask, };
