// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderModelCapabilityResponse } from "./ProviderModelCapabilityResponse";

/**
 * One provider model with all of its usable task capabilities nested in
 * deterministic task order.
 */
export type ProviderModelResponse = { provider_id: string, model: string,
/**
 * Optional human-readable label. Runtime invocation always uses `model`.
 */
display_name?: string, enabled: boolean, sort_order: number, description?: string, capabilities: Array<ProviderModelCapabilityResponse>, created_at: number, updated_at: number, };
