// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body identifying one row by its composite natural key
 * (`POST /api/provider-models/delete`).
 */
export type ProviderModelKeyRequest = { provider_id: string, model: string, };
