// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body identifying one model by its composite natural key.
 */
export type ProviderModelKeyRequest = { provider_id: string, model: string, };
