// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeEntryKind } from "./KnowledgeEntryKind";

/**
 * Durable receipt returned by drag/drop, "Move to…", and rename. One path
 * prefix pair is sufficient to update all descendants in UI consumers.
 */
export type RelocateKnowledgeEntryResponse = { operation_id: string, entry_id?: string, old_path: string, new_path: string, kind: KnowledgeEntryKind, moved_descendant_count: number, revision?: number, tree_revision: number, undo_token?: string, warnings?: Array<string>, };
