// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelocateKnowledgeEntryConflictPolicy } from "./RelocateKnowledgeEntryConflictPolicy";

/**
 * One idempotent move/rename command inside the knowledge base identified by
 * the route. Stable IDs are authoritative when present; paths are required as
 * locators for path-only clients and projection-degraded compatibility.
 */
export type RelocateKnowledgeEntryRequest = { request_id: string, source_path: string, destination_parent_path: string, entry_id?: string, destination_parent_id?: string, new_name?: string, expected_revision?: number, conflict_policy: RelocateKnowledgeEntryConflictPolicy, };
