// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";
import type { ModelTrait } from "./ModelTrait";

/**
 * Request body for `POST /api/model-profiles/resolve`.
 */
export type ResolveModelsRequest = { task: ModelTask, required_traits?: Array<ModelTrait>, };
