// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModelRef } from "./CatalogModelRef";

/**
 * Response body for `POST /api/model-profiles/resolve`.
 */
export type ResolveModelsResponse = { models: Array<CatalogModelRef>, };
