// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full metadata save for `PUT /api/providers/:id/connections`.
 *
 * Unlike aggregate creation, omitting `credentials` means preserve the
 * existing encrypted payload. The service rejects an omitted payload when
 * the `(provider_id, role)` row does not yet exist.
 */
export type SaveProviderConnectionRequest = { role: string, label?: string | null, base_url: string, auth_scheme: string,
/**
 * Omitted keeps an existing connection's encrypted credential payload.
 */
credentials?: unknown, extra?: unknown, };
