// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderModelInput } from "./ProviderModelInput";

/**
 * Upsert a provider model and replace its complete capability set atomically.
 */
export type SaveProviderModelRequest = { provider_id: string, model: ProviderModelInput, };
