// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderModelResponse } from "./ProviderModelResponse";

export type SyncModelGatewayResponse = { added: number, updated: number, models: Array<ProviderModelResponse>, };
