// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPlanStepStatus } from "./TaskPlanStepStatus";

export type TaskPlanStep = { step: string, status: TaskPlanStepStatus, };
