// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPlanStep } from "./TaskPlanStep";

export type TaskPlan = { revision: number, explanation: string, needs_replan: boolean, steps: Array<TaskPlanStep>, };
