// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPlan } from "./TaskPlan";

/**
 * One consistent read of the latest started turn, independently of transcript
 * pagination. A new turn without a plan explicitly clears the previous plan.
 */
export type TaskPlanSnapshot = { conversation_id: string, sequence: number, turn_id: string | null, turn_status: string | null, plan: TaskPlan | null, };
