// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `TurnCompleted` event — aggregate metrics for one turn.
 */
export type TurnCompletedEventData = { 
/**
 * Wall-clock duration of the turn in milliseconds.
 */
elapsed_ms: number, input_tokens: number, output_tokens: number, 
/**
 * Current context occupancy (last request's prompt tokens). Gauge numerator.
 */
context_tokens: number, 
/**
 * Effective context budget (engine compaction window). Gauge denominator.
 */
context_window: number, };
