// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cross-backend normalized "why did the turn end" reason. Deliberately NOT the
 * external protocol's own stop-reason enum, so the shared event type stays
 * engine-neutral; each backend maps its own outcome.
 */
export type TurnStopReason = "end_turn" | "max_tokens" | "max_turn_requests" | "refusal" | "cancelled";
