// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Idempotently reverse a previously committed relocate operation. The token
 * is opaque to clients and remains valid across process restarts because it
 * resolves through the durable mutation journal.
 */
export type UndoKnowledgeEntryRelocationRequest = { request_id: string, undo_token: string, };
