// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTask } from "./ModelTask";
import type { ModelTrait } from "./ModelTrait";

/**
 * Body for `POST /api/provider-models/update` — partial update of one row.
 *
 * Nullable columns use double-Option: field absent = keep, `null` = clear,
 * value = set.
 */
export type UpdateProviderModelRequest = { provider_id: string, model: string, enabled?: boolean, sort_order?: number, tasks?: Array<ModelTask>, traits?: Array<ModelTrait>, protocol?: string | null, connection_role?: string | null, params?: unknown, context_limit?: number | null, description?: string | null, };
