// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateModelGatewayConnectionRequest = { base_url: string, api_key?: string | null, name?: string | null, };
