// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpsertProviderConnectionRequest = { role: string, label?: string | null, base_url: string, auth_scheme?: string, 
/**
 * Write-only structured credentials (shape depends on auth_scheme),
 * encrypted at rest. `None` on update keeps the stored credentials.
 */
credentials?: unknown, is_full_url?: boolean, extra?: unknown, };
