#!/usr/bin/env bun
/**
 * ensure-ui-dist — placeholder for legacy Rust test entry points.
 *
 * The old desktop resource sidecar required ui/dist to exist even in dev.
 * That sidecar is no longer bundled: desktop and LAN production requests use
 * Tauri's embedded frontend, and development uses Vite. Existing Rust test
 * entry points still invoke this harmless, idempotent preflight; it does not
 * establish that production frontend assets or their build manifest are valid.
 *
 * What it does:
 *   If ui/dist is missing (or empty), create it with a tiny placeholder
 *   index.html. We DON'T do a real `vite build` here. A real production build
 *   still happens via tauri's beforeBuildCommand, which overwrites this
 *   placeholder. ui/dist is gitignored, so this is a local, regenerable artifact.
 *
 * Invariants: idempotent (no-op when a populated ui/dist already exists), cross-
 * platform (node:fs only, no shell), and never fatal to the dev chain.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'ui', 'dist');
const TAG = '[ensure-ui-dist]';

const log = (msg) => console.log(`${TAG} ${msg}`);

/** True when DIST exists and has at least one entry. */
function populated() {
  try {
    return existsSync(DIST) && readdirSync(DIST).length > 0;
  } catch {
    return false;
  }
}

const PLACEHOLDER = `<!doctype html>
<meta charset="utf-8">
<title>NomiFun — dev placeholder</title>
<!--
  Auto-generated by scripts/ensure-ui-dist.mjs for legacy Rust test preflight.
  In dev the real UI is served by Vite (http://localhost:5173).
  This placeholder is not a production frontend. \`bun run build:ui\`
  (and \`bun run build\`) overwrite ui/dist with the real production bundle.
-->
<body>NomiFun dev placeholder — run <code>bun run build:ui</code> for the real bundle.</body>
`;

try {
  if (populated()) {
    log('ui/dist present — ok');
  } else {
    mkdirSync(DIST, { recursive: true });
    writeFileSync(join(DIST, 'index.html'), PLACEHOLDER);
    log('ui/dist was missing — created placeholder (real bundle comes from `bun run build:ui`)');
  }
} catch (e) {
  // Never block the dev chain; surface the reason so a real failure is visible.
  log(`WARN: could not ensure ui/dist (${e.message}) — continuing`);
}

process.exit(0);
