[package]
name = "nomi-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
russh.workspace = true
russh-sftp.workspace = true
zeroize.workspace = true
tokio.workspace = true
async-trait.workspace = true
thiserror.workspace = true
tracing.workspace = true
regex.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros", "rt-multi-thread"] }
tempfile.workspace = true
